name: Develop branch action

on:                                                                              
  workflow_dispatch:                                                             
  push:
    paths:
      - "VERSION"
    branches:
      - develop

jobs:
  pull_request_main:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull Request
        run: >
          gh pr create -B master -H develop -ff
          --title 'Pull Request to Main' --body 'This pull request is automated github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
