name: Develop branch action

on:                                                                              
  workflow_dispatch:                                                             
  push:
    paths:
      - "VERSION"
    branches:
      - develop

jobs:
  pull_request_main:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Pull Request to Main"
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          body: >
            This pull request is automated github action by 
            [create-pull-request](https://github.com/peter-evans/create-pull-request).
          committer: GitHub <sungmu1@github.com>
          signoff: false
          commit-message: "Pull Request Message"
          assignees: sungmu1
          reviewers: sungmu1
          labels: |
            report
            automated pr
          branch: develop
          base: master
