name: Develop branch action

on:                                                                              
  workflow_dispatch:                                                             
  push:
    paths:
      - "VERSION"
    branches:
      - develop

jobs:
  pull_request_main:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "Pull Request to Main"
          token: ${{ secrets.GIT_ACCESS_TOKEN }}
          commit-message: "Pull Request Message"
          branch: main
