name: Main action

on:                                                                              
  workflow_dispatch:                                        
  pull_request_target:
    paths:
      - "VERSION"                                                              
    branches:                                                                    
      - master

jobs:
  close-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "Close Pull Request"
          github_token: ${{ secrets.GIT_ACCESS_TOKEN }}
  publish-galaxy:
    needs: close-pull-request
    uses: ./.github/workflows/publish-galaxy.yml
    secrets:
      galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
  trigger-gh-page-deploy:
    needs: [publish-galaxy, close-pull-request]
    runs-on: ubuntu-latest
    steps: 
      - run: |
          curl -XPOST -u "${{ secrets.ADMIN_USERNAME }}:${{ secrets.ADMIN_ACCESS_TOKEN }}" \
               -H "Accept: application/vnd.github.everest-preview+json" \
               -H "Content-Type: application/json" \
               https://api.github.com/repos/sungmu1/packer_test/dispatches \
               --data '{"event_type": "deploy-ansible-repository"}'
