name: Main action

on:                                                                              
  workflow_dispatch:                                        
  pull_request_target:
    types: [opened]
    paths:
      - "VERSION"                                                              
    branches:                                                                    
      - master

jobs:
  merge-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Automatically merge
        uses: "pascalgn/automerge-action@v0.15.5"
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_ACCESS_TOKEN }}
      - name: close-pull-request
        uses: superbrothers/close-pull-request@v3
        with:
          comment: "Close Pull Request"
          github_token: ${{ secrets.GIT_ACCESS_TOKEN }}
